default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "onmangequoi") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "onmangequoi") %>

development:
  <<: *default
  database: onmangequoicesoir_dev
  port: <%= ENV.fetch("DATABASE_PORT", 5454) %>

test:
  <<: *default
  database: onmangequoicesoir_test
  port: <%= ENV.fetch("TEST_DATABASE_PORT") { ENV.fetch("DATABASE_PORT", 5455) } %>

production:
  <<: *default
  database: onmangequoicesoir_prod
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
